import { chipStyle as __pure_chipStyle } from './chip-style.mjs';
// צילום-מקומי + עטיפת-כריכה (מנוע-הטיהור v3)
const __d_chipStyle_CHIP_STYLE_T = {
  k1: "inline-block",
  k2: "nowrap",
  k3: 999,
  k4: 12,
  k5: 700,
};
const chipStyle = (...a) => __pure_chipStyle(...a, ...Array(Math.max(0, 2 - a.length)).fill(undefined), __d_chipStyle_CHIP_STYLE_T);
const CASES = [[["\"\"","\"\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"אבג\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"אבג\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"כהן לוי\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"כהן לוי\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"abc\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"abc\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"a@b.com\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"a@b.com\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"2026-08-24\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"2026-08-24\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"2026-08-24T12:00:00\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"2026-08-24T12:00:00\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"0501234567\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"0501234567\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"03-1234567\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"03-1234567\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"https://x.co\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"https://x.co\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"שלום עולם\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"שלום עולם\",\"whiteSpace\":\"nowrap\"}"],[["\"\"","\"12\""],"{\"display\":\"inline-block\",\"padding\":\"3px 10px\",\"borderRadius\":999,\"fontSize\":12,\"fontWeight\":700,\"background\":\"\",\"color\":\"12\",\"whiteSpace\":\"nowrap\"}"]];
const de = (s) => s === '"__undef__"' ? undefined : JSON.parse(s);
let f = 0;
for (const [args, want] of CASES) { const got = JSON.stringify(chipStyle(...args.map(de))); if (got !== want) { console.error('✗ ' + args + ' ⇒ ' + got + ' ≠ ' + want); f = 1; } }
if (f) process.exit(1); console.log('✓ chip-style: ' + CASES.length + ' הקלטות-Golden — ירוק');
