import { makeXLAT as __pure_makeXLAT, expandQuery as __pure_expandQuery } from './xlat.mjs';
// צילום-מקומי + עטיפת-כריכה (מנוע-הקשיחים; בדיקה לא מייבאת אטום-שכן)
const __d_xlat_T = {
  k1: "כהן",
  k2: "cohen",
  k3: "kohen",
  k4: "לוי",
  k5: "levi",
  k6: "מזרחי",
  k7: "mizrahi",
  k8: "פרידמן",
  k9: "fridman",
  k10: "friedman",
  k11: "אברמוב",
  k12: "abramov",
  k13: "שרעבי",
  k14: "sharabi",
  k15: "גולדשטיין",
  k16: "goldstein",
  k17: "בן דוד",
  k18: "bendavid",
  k19: "ben david",
  k20: "אוחיון",
  k21: "ohayon",
  k22: "משה",
  k23: "moshe",
  k24: "מוישי",
  k25: "מוישה",
  k26: "שרה",
  k27: "sara",
  k28: "sarah",
  k29: "שרהלה",
  k30: "דוד",
  k31: "david",
  k32: "דודי",
  k33: "תמר",
  k34: "tamar",
  k35: "יוסף",
  k36: "yosef",
  k37: "יוסי",
  k38: "רחל",
  k39: "rachel",
  k40: "רחלי",
  k41: "בנימין",
  k42: "binyamin",
  k43: "בני",
  k44: "נועה",
  k45: "noa",
  k46: "איתן",
  k47: "eitan",
  k48: "הודיה",
  k49: "hodaya",
  k50: "מיכאל",
  k51: "michael",
  k52: "מיכי",
  k53: "ליאה",
  k54: "lea",
  k55: "יונתן",
  k56: "yonatan",
  k57: "יוני",
  k58: "אבישי",
  k59: "avishai",
  k60: "טליה",
  k61: "talia",
  k62: "עומר",
  k63: "omer",
  k64: "אגם",
  k65: "agam",
  k66: "ליאם",
  k67: "liam",
  k68: "רומי",
  k69: "romi",
  k70: "אליה",
  k71: "eliya",
  k72: "צבי",
  k73: "zvi",
  k74: "אסתר",
  k75: "esther",
  k76: "אסתי",
  k77: "כינור",
  k78: "violin",
  k79: "גיטרה",
  k80: "guitar",
  k81: "פסנתר",
  k82: "piano",
  k83: "פסנטר",
  k84: "אורגנית",
  k85: "organ",
  k86: "אורגן",
  k87: "מסאז׳",
  k88: "massage",
  k89: "מסאז",
  k90: "עיסוי",
  k91: "גרפיקה",
  k92: "graphics",
  k93: "פיתוח קול",
  k94: "vocal",
  k95: "שירה",
  k96: "אומנות",
  k97: "art",
  k98: "אמנות",
  k99: "צילום",
  k100: "photo",
  k101: "photography",
  k102: "מצלמה",
  k103: "ספרות",
  k104: "writing",
  k105: "כתיבה",
  k106: "ספר",
  k107: "אפייה",
  k108: "baking",
  k109: "בישול",
  k110: "קונדיטוריה",
  k111: "אנגלית",
  k112: "english",
  k113: "שפה",
  k114: "העצמה",
  k115: "empowerment",
  k116: "ביטחון עצמי",
  k117: "התעמלות",
  k118: "fitness",
  k119: "ספורט",
  k120: "כושר",
  k121: "ג׳ים",
  k122: "רפלקסולוגיה",
  k123: "reflexology",
  k124: "ציור",
  k125: "יצירה",
  k126: "תפירה",
  k127: "sewing",
  k128: "מחט",
  k129: "אפילציה",
  k130: "epilation",
  k131: "טיפוח",
  k132: "מוזיקה",
  k133: "music",
  k134: "נגינה",
  k135: "ירושלים",
  k136: "jerusalem",
  k137: "בני ברק",
  k138: "bnei brak",
  k139: "פתח תקווה",
  k140: "petah tikva",
  k141: "ראש העין",
  k142: "rosh haayin",
  k143: "מודיעין עילית",
  k144: "modiin illit",
  k145: "ביתר עילית",
  k146: "beitar illit",
};
const XLAT = __pure_makeXLAT(__d_xlat_T);
const expandQuery = (...a) => __pure_expandQuery(...a, ...Array(Math.max(0, 2 - a.length)).fill(undefined), __d_xlat_T);
const norm = (t) => String(t||'').toLowerCase().replace(/[֑-ׇ]/g,'').replace(/[ךםןףץ]/g,(c)=>({ך:'כ',ם:'מ',ן:'נ',ף:'פ',ץ:'צ'})[c]).replace(/['"׳״\-–._]/g,'').trim();
let f=0;
const has=(q,x)=>expandQuery(q,norm).includes(x);
if(!has('כהן','cohen')||!has('כהן','коэн')){console.error('✗ כהן לא מתרחב');f=1;}
if(!has('cohen','כהן')){console.error('✗ כיוון-הפוך נכשל');f=1;}
if(!has('משה','מוישי')){console.error('✗ כינוי חסר');f=1;}
if(expandQuery('xyz',norm).length!==1){console.error('✗ לא-מוכר חייב להישאר לבד');f=1;}
if(expandQuery('כהן',norm)[0]!=='כהן'){console.error('✗ המקור חייב להיות ראשון');f=1;}
if(Object.keys(XLAT).length<20){console.error('✗ הטבלה נחתכה');f=1;}
if(f)process.exit(1); console.log('✓ xlat: 6 בדיקות-חוזה — ירוק (טבלה: '+Object.keys(XLAT).length+' ערכים)');
