// ✨ חולל ע"י מנוע-הרינדור (render-ds) — דשבורד מנתוני-הישויות החיים. אל תערוך ידנית.
import '../dart-data-bs/auto/gen_app_scr72_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import 'package:flutter/material.dart';

class GenAppScr72Screen extends StatelessWidget {
  const GenAppScr72Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return DsScaffold(
      title: gen_app_scr72_c0,
      subtitle: gen_app_scr72_c1,
      icon: gen_app_scr72_c2,
      children: [
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c3, value: appStore.count(gen_app_scr72_c3).toString(), sub: gen_app_scr72_c4, glyph: gen_app_scr72_c5))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c6, value: appStore.count(gen_app_scr72_c6).toString(), sub: gen_app_scr72_c7, glyph: gen_app_scr72_c8)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c9, value: appStore.count(gen_app_scr72_c9).toString(), sub: gen_app_scr72_c10, glyph: gen_app_scr72_c11))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c12, value: appStore.count(gen_app_scr72_c12).toString(), sub: gen_app_scr72_c13, glyph: gen_app_scr72_c14)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c15, value: appStore.count(gen_app_scr72_c15).toString(), sub: gen_app_scr72_c16, glyph: gen_app_scr72_c17))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c18, value: appStore.count(gen_app_scr72_c18).toString(), sub: gen_app_scr72_c19, glyph: gen_app_scr72_c20)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c21, value: appStore.count(gen_app_scr72_c21).toString(), sub: gen_app_scr72_c22, glyph: gen_app_scr72_c23))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c24, value: appStore.count(gen_app_scr72_c24).toString(), sub: gen_app_scr72_c25, glyph: gen_app_scr72_c26)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c27, value: appStore.count(gen_app_scr72_c27).toString(), sub: gen_app_scr72_c28, glyph: gen_app_scr72_c29))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c30, value: appStore.count(gen_app_scr72_c30).toString(), sub: gen_app_scr72_c31, glyph: gen_app_scr72_c32)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c33, value: appStore.count(gen_app_scr72_c33).toString(), sub: gen_app_scr72_c34, glyph: gen_app_scr72_c35))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c36, value: appStore.count(gen_app_scr72_c36).toString(), sub: gen_app_scr72_c37, glyph: gen_app_scr72_c38)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c39, value: appStore.count(gen_app_scr72_c39).toString(), sub: gen_app_scr72_c40, glyph: gen_app_scr72_c41))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c42, value: appStore.count(gen_app_scr72_c42).toString(), sub: gen_app_scr72_c43, glyph: gen_app_scr72_c44)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c45, value: appStore.count(gen_app_scr72_c45).toString(), sub: gen_app_scr72_c46, glyph: gen_app_scr72_c47))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c48, value: appStore.count(gen_app_scr72_c48).toString(), sub: gen_app_scr72_c49, glyph: gen_app_scr72_c50)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c51, value: appStore.count(gen_app_scr72_c51).toString(), sub: gen_app_scr72_c52, glyph: gen_app_scr72_c53))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c54, value: appStore.count(gen_app_scr72_c54).toString(), sub: gen_app_scr72_c55, glyph: gen_app_scr72_c56)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c57, value: appStore.count(gen_app_scr72_c57).toString(), sub: gen_app_scr72_c58, glyph: gen_app_scr72_c59))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c60, value: appStore.count(gen_app_scr72_c60).toString(), sub: gen_app_scr72_c61, glyph: gen_app_scr72_c62)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c63, value: appStore.count(gen_app_scr72_c63).toString(), sub: gen_app_scr72_c64, glyph: gen_app_scr72_c65))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c66, value: appStore.count(gen_app_scr72_c66).toString(), sub: gen_app_scr72_c67, glyph: gen_app_scr72_c68)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c69, value: appStore.count(gen_app_scr72_c69).toString(), sub: gen_app_scr72_c70, glyph: gen_app_scr72_c71))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c72, value: appStore.count(gen_app_scr72_c72).toString(), sub: gen_app_scr72_c73, glyph: gen_app_scr72_c74)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c75, value: appStore.count(gen_app_scr72_c75).toString(), sub: gen_app_scr72_c76, glyph: gen_app_scr72_c77))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c78, value: appStore.count(gen_app_scr72_c78).toString(), sub: gen_app_scr72_c79, glyph: gen_app_scr72_c80)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c81, value: appStore.count(gen_app_scr72_c81).toString(), sub: gen_app_scr72_c82, glyph: gen_app_scr72_c83))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c84, value: appStore.count(gen_app_scr72_c84).toString(), sub: gen_app_scr72_c85, glyph: gen_app_scr72_c86)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c87, value: appStore.count(gen_app_scr72_c87).toString(), sub: gen_app_scr72_c88, glyph: gen_app_scr72_c89))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c90, value: appStore.count(gen_app_scr72_c90).toString(), sub: gen_app_scr72_c91, glyph: gen_app_scr72_c92)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c93, value: appStore.count(gen_app_scr72_c93).toString(), sub: gen_app_scr72_c94, glyph: gen_app_scr72_c95))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c96, value: appStore.count(gen_app_scr72_c96).toString(), sub: gen_app_scr72_c97, glyph: gen_app_scr72_c98)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c99, value: appStore.count(gen_app_scr72_c99).toString(), sub: gen_app_scr72_c100, glyph: gen_app_scr72_c101))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c102, value: appStore.count(gen_app_scr72_c102).toString(), sub: gen_app_scr72_c103, glyph: gen_app_scr72_c104)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c105, value: appStore.count(gen_app_scr72_c105).toString(), sub: gen_app_scr72_c106, glyph: gen_app_scr72_c107))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c108, value: appStore.count(gen_app_scr72_c108).toString(), sub: gen_app_scr72_c109, glyph: gen_app_scr72_c110)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c111, value: appStore.count(gen_app_scr72_c111).toString(), sub: gen_app_scr72_c112, glyph: gen_app_scr72_c113))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c114, value: appStore.count(gen_app_scr72_c114).toString(), sub: gen_app_scr72_c115, glyph: gen_app_scr72_c116)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c117, value: appStore.count(gen_app_scr72_c117).toString(), sub: gen_app_scr72_c118, glyph: gen_app_scr72_c119))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c120, value: appStore.count(gen_app_scr72_c120).toString(), sub: gen_app_scr72_c121, glyph: gen_app_scr72_c122)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c123, value: appStore.count(gen_app_scr72_c123).toString(), sub: gen_app_scr72_c124, glyph: gen_app_scr72_c125))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c126, value: appStore.count(gen_app_scr72_c126).toString(), sub: gen_app_scr72_c127, glyph: gen_app_scr72_c128)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c129, value: appStore.count(gen_app_scr72_c129).toString(), sub: gen_app_scr72_c130, glyph: gen_app_scr72_c131))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c132, value: appStore.count(gen_app_scr72_c132).toString(), sub: gen_app_scr72_c133, glyph: gen_app_scr72_c134)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c135, value: appStore.count(gen_app_scr72_c135).toString(), sub: gen_app_scr72_c136, glyph: gen_app_scr72_c137))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c138, value: appStore.count(gen_app_scr72_c138).toString(), sub: gen_app_scr72_c139, glyph: gen_app_scr72_c140)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c141, value: appStore.count(gen_app_scr72_c141).toString(), sub: gen_app_scr72_c142, glyph: gen_app_scr72_c143))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c144, value: appStore.count(gen_app_scr72_c144).toString(), sub: gen_app_scr72_c145, glyph: gen_app_scr72_c146)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c147, value: appStore.count(gen_app_scr72_c147).toString(), sub: gen_app_scr72_c148, glyph: gen_app_scr72_c149))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c150, value: appStore.count(gen_app_scr72_c150).toString(), sub: gen_app_scr72_c151, glyph: gen_app_scr72_c152)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c153, value: appStore.count(gen_app_scr72_c153).toString(), sub: gen_app_scr72_c154, glyph: gen_app_scr72_c155))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c156, value: appStore.count(gen_app_scr72_c156).toString(), sub: gen_app_scr72_c157, glyph: gen_app_scr72_c158)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c159, value: appStore.count(gen_app_scr72_c159).toString(), sub: gen_app_scr72_c160, glyph: gen_app_scr72_c161))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c162, value: appStore.count(gen_app_scr72_c162).toString(), sub: gen_app_scr72_c163, glyph: gen_app_scr72_c164)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c165, value: appStore.count(gen_app_scr72_c165).toString(), sub: gen_app_scr72_c166, glyph: gen_app_scr72_c167))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c168, value: appStore.count(gen_app_scr72_c168).toString(), sub: gen_app_scr72_c169, glyph: gen_app_scr72_c170)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c171, value: appStore.count(gen_app_scr72_c171).toString(), sub: gen_app_scr72_c172, glyph: gen_app_scr72_c173))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c174, value: appStore.count(gen_app_scr72_c174).toString(), sub: gen_app_scr72_c175, glyph: gen_app_scr72_c176)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c177, value: appStore.count(gen_app_scr72_c177).toString(), sub: gen_app_scr72_c178, glyph: gen_app_scr72_c179))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c180, value: appStore.count(gen_app_scr72_c180).toString(), sub: gen_app_scr72_c181, glyph: gen_app_scr72_c182)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c183, value: appStore.count(gen_app_scr72_c183).toString(), sub: gen_app_scr72_c184, glyph: gen_app_scr72_c185))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c186, value: appStore.count(gen_app_scr72_c186).toString(), sub: gen_app_scr72_c187, glyph: gen_app_scr72_c188)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c189, value: appStore.count(gen_app_scr72_c189).toString(), sub: gen_app_scr72_c190, glyph: gen_app_scr72_c191))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c192, value: appStore.count(gen_app_scr72_c192).toString(), sub: gen_app_scr72_c193, glyph: gen_app_scr72_c194)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c195, value: appStore.count(gen_app_scr72_c195).toString(), sub: gen_app_scr72_c196, glyph: gen_app_scr72_c197))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c198, value: appStore.count(gen_app_scr72_c198).toString(), sub: gen_app_scr72_c199, glyph: gen_app_scr72_c200)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c201, value: appStore.count(gen_app_scr72_c201).toString(), sub: gen_app_scr72_c202, glyph: gen_app_scr72_c203))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c204, value: appStore.count(gen_app_scr72_c204).toString(), sub: gen_app_scr72_c205, glyph: gen_app_scr72_c206)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c207, value: appStore.count(gen_app_scr72_c207).toString(), sub: gen_app_scr72_c208, glyph: gen_app_scr72_c209))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c210, value: appStore.count(gen_app_scr72_c210).toString(), sub: gen_app_scr72_c211, glyph: gen_app_scr72_c212)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr72_c213, value: appStore.count(gen_app_scr72_c213).toString(), sub: gen_app_scr72_c214, glyph: gen_app_scr72_c215))), const SizedBox(width: 12), const Expanded(child: SizedBox())]))),
      ],
    );
  }
}
