// ✨ חולל ע"י מנוע-הרינדור (render-ds) — דשבורד מנתוני-הישויות החיים. אל תערוך ידנית.
import '../dart-data-bs/auto/gen_app_scr76_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import 'package:flutter/material.dart';

class GenAppScr76Screen extends StatelessWidget {
  const GenAppScr76Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return DsScaffold(
      title: gen_app_scr76_c0,
      subtitle: gen_app_scr76_c1,
      icon: gen_app_scr76_c2,
      children: [
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c3, value: appStore.count(gen_app_scr76_c3).toString(), sub: gen_app_scr76_c4, glyph: gen_app_scr76_c5))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c6, value: appStore.count(gen_app_scr76_c6).toString(), sub: gen_app_scr76_c7, glyph: gen_app_scr76_c8)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c9, value: appStore.count(gen_app_scr76_c9).toString(), sub: gen_app_scr76_c10, glyph: gen_app_scr76_c11))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c12, value: appStore.count(gen_app_scr76_c12).toString(), sub: gen_app_scr76_c13, glyph: gen_app_scr76_c14)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c15, value: appStore.count(gen_app_scr76_c15).toString(), sub: gen_app_scr76_c16, glyph: gen_app_scr76_c17))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c18, value: appStore.count(gen_app_scr76_c18).toString(), sub: gen_app_scr76_c19, glyph: gen_app_scr76_c20)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c21, value: appStore.count(gen_app_scr76_c21).toString(), sub: gen_app_scr76_c22, glyph: gen_app_scr76_c23))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c24, value: appStore.count(gen_app_scr76_c24).toString(), sub: gen_app_scr76_c25, glyph: gen_app_scr76_c26)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c27, value: appStore.count(gen_app_scr76_c27).toString(), sub: gen_app_scr76_c28, glyph: gen_app_scr76_c29))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c30, value: appStore.count(gen_app_scr76_c30).toString(), sub: gen_app_scr76_c31, glyph: gen_app_scr76_c32)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c33, value: appStore.count(gen_app_scr76_c33).toString(), sub: gen_app_scr76_c34, glyph: gen_app_scr76_c35))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c36, value: appStore.count(gen_app_scr76_c36).toString(), sub: gen_app_scr76_c37, glyph: gen_app_scr76_c38)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c39, value: appStore.count(gen_app_scr76_c39).toString(), sub: gen_app_scr76_c40, glyph: gen_app_scr76_c41))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c42, value: appStore.count(gen_app_scr76_c42).toString(), sub: gen_app_scr76_c43, glyph: gen_app_scr76_c44)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c45, value: appStore.count(gen_app_scr76_c45).toString(), sub: gen_app_scr76_c46, glyph: gen_app_scr76_c47))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c48, value: appStore.count(gen_app_scr76_c48).toString(), sub: gen_app_scr76_c49, glyph: gen_app_scr76_c50)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c51, value: appStore.count(gen_app_scr76_c51).toString(), sub: gen_app_scr76_c52, glyph: gen_app_scr76_c53))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c54, value: appStore.count(gen_app_scr76_c54).toString(), sub: gen_app_scr76_c55, glyph: gen_app_scr76_c56)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c57, value: appStore.count(gen_app_scr76_c57).toString(), sub: gen_app_scr76_c58, glyph: gen_app_scr76_c59))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c60, value: appStore.count(gen_app_scr76_c60).toString(), sub: gen_app_scr76_c61, glyph: gen_app_scr76_c62)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c63, value: appStore.count(gen_app_scr76_c63).toString(), sub: gen_app_scr76_c64, glyph: gen_app_scr76_c65))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c66, value: appStore.count(gen_app_scr76_c66).toString(), sub: gen_app_scr76_c67, glyph: gen_app_scr76_c68)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c69, value: appStore.count(gen_app_scr76_c69).toString(), sub: gen_app_scr76_c70, glyph: gen_app_scr76_c71))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c72, value: appStore.count(gen_app_scr76_c72).toString(), sub: gen_app_scr76_c73, glyph: gen_app_scr76_c74)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c75, value: appStore.count(gen_app_scr76_c75).toString(), sub: gen_app_scr76_c76, glyph: gen_app_scr76_c77))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c78, value: appStore.count(gen_app_scr76_c78).toString(), sub: gen_app_scr76_c79, glyph: gen_app_scr76_c80)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c81, value: appStore.count(gen_app_scr76_c81).toString(), sub: gen_app_scr76_c82, glyph: gen_app_scr76_c83))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c84, value: appStore.count(gen_app_scr76_c84).toString(), sub: gen_app_scr76_c85, glyph: gen_app_scr76_c86)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c87, value: appStore.count(gen_app_scr76_c87).toString(), sub: gen_app_scr76_c88, glyph: gen_app_scr76_c89))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c90, value: appStore.count(gen_app_scr76_c90).toString(), sub: gen_app_scr76_c91, glyph: gen_app_scr76_c92)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c93, value: appStore.count(gen_app_scr76_c93).toString(), sub: gen_app_scr76_c94, glyph: gen_app_scr76_c95))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c96, value: appStore.count(gen_app_scr76_c96).toString(), sub: gen_app_scr76_c97, glyph: gen_app_scr76_c98)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c99, value: appStore.count(gen_app_scr76_c99).toString(), sub: gen_app_scr76_c100, glyph: gen_app_scr76_c101))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c102, value: appStore.count(gen_app_scr76_c102).toString(), sub: gen_app_scr76_c103, glyph: gen_app_scr76_c104)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c105, value: appStore.count(gen_app_scr76_c105).toString(), sub: gen_app_scr76_c106, glyph: gen_app_scr76_c107))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c108, value: appStore.count(gen_app_scr76_c108).toString(), sub: gen_app_scr76_c109, glyph: gen_app_scr76_c110)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c111, value: appStore.count(gen_app_scr76_c111).toString(), sub: gen_app_scr76_c112, glyph: gen_app_scr76_c113))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c114, value: appStore.count(gen_app_scr76_c114).toString(), sub: gen_app_scr76_c115, glyph: gen_app_scr76_c116)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c117, value: appStore.count(gen_app_scr76_c117).toString(), sub: gen_app_scr76_c118, glyph: gen_app_scr76_c119))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c120, value: appStore.count(gen_app_scr76_c120).toString(), sub: gen_app_scr76_c121, glyph: gen_app_scr76_c122)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c123, value: appStore.count(gen_app_scr76_c123).toString(), sub: gen_app_scr76_c124, glyph: gen_app_scr76_c125))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c126, value: appStore.count(gen_app_scr76_c126).toString(), sub: gen_app_scr76_c127, glyph: gen_app_scr76_c128)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c129, value: appStore.count(gen_app_scr76_c129).toString(), sub: gen_app_scr76_c130, glyph: gen_app_scr76_c131))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c132, value: appStore.count(gen_app_scr76_c132).toString(), sub: gen_app_scr76_c133, glyph: gen_app_scr76_c134)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c135, value: appStore.count(gen_app_scr76_c135).toString(), sub: gen_app_scr76_c136, glyph: gen_app_scr76_c137))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c138, value: appStore.count(gen_app_scr76_c138).toString(), sub: gen_app_scr76_c139, glyph: gen_app_scr76_c140)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c141, value: appStore.count(gen_app_scr76_c141).toString(), sub: gen_app_scr76_c142, glyph: gen_app_scr76_c143))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c144, value: appStore.count(gen_app_scr76_c144).toString(), sub: gen_app_scr76_c145, glyph: gen_app_scr76_c146)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c147, value: appStore.count(gen_app_scr76_c147).toString(), sub: gen_app_scr76_c148, glyph: gen_app_scr76_c149))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c150, value: appStore.count(gen_app_scr76_c150).toString(), sub: gen_app_scr76_c151, glyph: gen_app_scr76_c152)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c153, value: appStore.count(gen_app_scr76_c153).toString(), sub: gen_app_scr76_c154, glyph: gen_app_scr76_c155))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c156, value: appStore.count(gen_app_scr76_c156).toString(), sub: gen_app_scr76_c157, glyph: gen_app_scr76_c158)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c159, value: appStore.count(gen_app_scr76_c159).toString(), sub: gen_app_scr76_c160, glyph: gen_app_scr76_c161))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c162, value: appStore.count(gen_app_scr76_c162).toString(), sub: gen_app_scr76_c163, glyph: gen_app_scr76_c164)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c165, value: appStore.count(gen_app_scr76_c165).toString(), sub: gen_app_scr76_c166, glyph: gen_app_scr76_c167))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c168, value: appStore.count(gen_app_scr76_c168).toString(), sub: gen_app_scr76_c169, glyph: gen_app_scr76_c170)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c171, value: appStore.count(gen_app_scr76_c171).toString(), sub: gen_app_scr76_c172, glyph: gen_app_scr76_c173))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c174, value: appStore.count(gen_app_scr76_c174).toString(), sub: gen_app_scr76_c175, glyph: gen_app_scr76_c176)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c177, value: appStore.count(gen_app_scr76_c177).toString(), sub: gen_app_scr76_c178, glyph: gen_app_scr76_c179))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c180, value: appStore.count(gen_app_scr76_c180).toString(), sub: gen_app_scr76_c181, glyph: gen_app_scr76_c182)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c183, value: appStore.count(gen_app_scr76_c183).toString(), sub: gen_app_scr76_c184, glyph: gen_app_scr76_c185))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c186, value: appStore.count(gen_app_scr76_c186).toString(), sub: gen_app_scr76_c187, glyph: gen_app_scr76_c188)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c189, value: appStore.count(gen_app_scr76_c189).toString(), sub: gen_app_scr76_c190, glyph: gen_app_scr76_c191))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c192, value: appStore.count(gen_app_scr76_c192).toString(), sub: gen_app_scr76_c193, glyph: gen_app_scr76_c194)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c195, value: appStore.count(gen_app_scr76_c195).toString(), sub: gen_app_scr76_c196, glyph: gen_app_scr76_c197))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c198, value: appStore.count(gen_app_scr76_c198).toString(), sub: gen_app_scr76_c199, glyph: gen_app_scr76_c200)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c201, value: appStore.count(gen_app_scr76_c201).toString(), sub: gen_app_scr76_c202, glyph: gen_app_scr76_c203))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c204, value: appStore.count(gen_app_scr76_c204).toString(), sub: gen_app_scr76_c205, glyph: gen_app_scr76_c206)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c207, value: appStore.count(gen_app_scr76_c207).toString(), sub: gen_app_scr76_c208, glyph: gen_app_scr76_c209))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c210, value: appStore.count(gen_app_scr76_c210).toString(), sub: gen_app_scr76_c211, glyph: gen_app_scr76_c212)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr76_c213, value: appStore.count(gen_app_scr76_c213).toString(), sub: gen_app_scr76_c214, glyph: gen_app_scr76_c215))), const SizedBox(width: 12), const Expanded(child: SizedBox())]))),
      ],
    );
  }
}
