// ✨ חולל ע"י מנוע-הרינדור (render-ds) — דשבורד מנתוני-הישויות החיים. אל תערוך ידנית.
import '../dart-data-bs/auto/gen_app_scr75_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import 'package:flutter/material.dart';

class GenAppScr75Screen extends StatelessWidget {
  const GenAppScr75Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return DsScaffold(
      title: gen_app_scr75_c0,
      subtitle: gen_app_scr75_c1,
      icon: gen_app_scr75_c2,
      children: [
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c3, value: appStore.count(gen_app_scr75_c3).toString(), sub: gen_app_scr75_c4, glyph: gen_app_scr75_c5))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c6, value: appStore.count(gen_app_scr75_c6).toString(), sub: gen_app_scr75_c7, glyph: gen_app_scr75_c8)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c9, value: appStore.count(gen_app_scr75_c9).toString(), sub: gen_app_scr75_c10, glyph: gen_app_scr75_c11))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c12, value: appStore.count(gen_app_scr75_c12).toString(), sub: gen_app_scr75_c13, glyph: gen_app_scr75_c14)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c15, value: appStore.count(gen_app_scr75_c15).toString(), sub: gen_app_scr75_c16, glyph: gen_app_scr75_c17))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c18, value: appStore.count(gen_app_scr75_c18).toString(), sub: gen_app_scr75_c19, glyph: gen_app_scr75_c20)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c21, value: appStore.count(gen_app_scr75_c21).toString(), sub: gen_app_scr75_c22, glyph: gen_app_scr75_c23))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c24, value: appStore.count(gen_app_scr75_c24).toString(), sub: gen_app_scr75_c25, glyph: gen_app_scr75_c26)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c27, value: appStore.count(gen_app_scr75_c27).toString(), sub: gen_app_scr75_c28, glyph: gen_app_scr75_c29))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c30, value: appStore.count(gen_app_scr75_c30).toString(), sub: gen_app_scr75_c31, glyph: gen_app_scr75_c32)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c33, value: appStore.count(gen_app_scr75_c33).toString(), sub: gen_app_scr75_c34, glyph: gen_app_scr75_c35))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c36, value: appStore.count(gen_app_scr75_c36).toString(), sub: gen_app_scr75_c37, glyph: gen_app_scr75_c38)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c39, value: appStore.count(gen_app_scr75_c39).toString(), sub: gen_app_scr75_c40, glyph: gen_app_scr75_c41))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c42, value: appStore.count(gen_app_scr75_c42).toString(), sub: gen_app_scr75_c43, glyph: gen_app_scr75_c44)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c45, value: appStore.count(gen_app_scr75_c45).toString(), sub: gen_app_scr75_c46, glyph: gen_app_scr75_c47))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c48, value: appStore.count(gen_app_scr75_c48).toString(), sub: gen_app_scr75_c49, glyph: gen_app_scr75_c50)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c51, value: appStore.count(gen_app_scr75_c51).toString(), sub: gen_app_scr75_c52, glyph: gen_app_scr75_c53))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c54, value: appStore.count(gen_app_scr75_c54).toString(), sub: gen_app_scr75_c55, glyph: gen_app_scr75_c56)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c57, value: appStore.count(gen_app_scr75_c57).toString(), sub: gen_app_scr75_c58, glyph: gen_app_scr75_c59))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c60, value: appStore.count(gen_app_scr75_c60).toString(), sub: gen_app_scr75_c61, glyph: gen_app_scr75_c62)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c63, value: appStore.count(gen_app_scr75_c63).toString(), sub: gen_app_scr75_c64, glyph: gen_app_scr75_c65))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c66, value: appStore.count(gen_app_scr75_c66).toString(), sub: gen_app_scr75_c67, glyph: gen_app_scr75_c68)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c69, value: appStore.count(gen_app_scr75_c69).toString(), sub: gen_app_scr75_c70, glyph: gen_app_scr75_c71))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c72, value: appStore.count(gen_app_scr75_c72).toString(), sub: gen_app_scr75_c73, glyph: gen_app_scr75_c74)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c75, value: appStore.count(gen_app_scr75_c75).toString(), sub: gen_app_scr75_c76, glyph: gen_app_scr75_c77))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c78, value: appStore.count(gen_app_scr75_c78).toString(), sub: gen_app_scr75_c79, glyph: gen_app_scr75_c80)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c81, value: appStore.count(gen_app_scr75_c81).toString(), sub: gen_app_scr75_c82, glyph: gen_app_scr75_c83))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c84, value: appStore.count(gen_app_scr75_c84).toString(), sub: gen_app_scr75_c85, glyph: gen_app_scr75_c86)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c87, value: appStore.count(gen_app_scr75_c87).toString(), sub: gen_app_scr75_c88, glyph: gen_app_scr75_c89))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c90, value: appStore.count(gen_app_scr75_c90).toString(), sub: gen_app_scr75_c91, glyph: gen_app_scr75_c92)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c93, value: appStore.count(gen_app_scr75_c93).toString(), sub: gen_app_scr75_c94, glyph: gen_app_scr75_c95))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c96, value: appStore.count(gen_app_scr75_c96).toString(), sub: gen_app_scr75_c97, glyph: gen_app_scr75_c98)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c99, value: appStore.count(gen_app_scr75_c99).toString(), sub: gen_app_scr75_c100, glyph: gen_app_scr75_c101))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c102, value: appStore.count(gen_app_scr75_c102).toString(), sub: gen_app_scr75_c103, glyph: gen_app_scr75_c104)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c105, value: appStore.count(gen_app_scr75_c105).toString(), sub: gen_app_scr75_c106, glyph: gen_app_scr75_c107))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c108, value: appStore.count(gen_app_scr75_c108).toString(), sub: gen_app_scr75_c109, glyph: gen_app_scr75_c110)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c111, value: appStore.count(gen_app_scr75_c111).toString(), sub: gen_app_scr75_c112, glyph: gen_app_scr75_c113))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c114, value: appStore.count(gen_app_scr75_c114).toString(), sub: gen_app_scr75_c115, glyph: gen_app_scr75_c116)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c117, value: appStore.count(gen_app_scr75_c117).toString(), sub: gen_app_scr75_c118, glyph: gen_app_scr75_c119))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c120, value: appStore.count(gen_app_scr75_c120).toString(), sub: gen_app_scr75_c121, glyph: gen_app_scr75_c122)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c123, value: appStore.count(gen_app_scr75_c123).toString(), sub: gen_app_scr75_c124, glyph: gen_app_scr75_c125))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c126, value: appStore.count(gen_app_scr75_c126).toString(), sub: gen_app_scr75_c127, glyph: gen_app_scr75_c128)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c129, value: appStore.count(gen_app_scr75_c129).toString(), sub: gen_app_scr75_c130, glyph: gen_app_scr75_c131))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c132, value: appStore.count(gen_app_scr75_c132).toString(), sub: gen_app_scr75_c133, glyph: gen_app_scr75_c134)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c135, value: appStore.count(gen_app_scr75_c135).toString(), sub: gen_app_scr75_c136, glyph: gen_app_scr75_c137))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c138, value: appStore.count(gen_app_scr75_c138).toString(), sub: gen_app_scr75_c139, glyph: gen_app_scr75_c140)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c141, value: appStore.count(gen_app_scr75_c141).toString(), sub: gen_app_scr75_c142, glyph: gen_app_scr75_c143))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c144, value: appStore.count(gen_app_scr75_c144).toString(), sub: gen_app_scr75_c145, glyph: gen_app_scr75_c146)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c147, value: appStore.count(gen_app_scr75_c147).toString(), sub: gen_app_scr75_c148, glyph: gen_app_scr75_c149))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c150, value: appStore.count(gen_app_scr75_c150).toString(), sub: gen_app_scr75_c151, glyph: gen_app_scr75_c152)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c153, value: appStore.count(gen_app_scr75_c153).toString(), sub: gen_app_scr75_c154, glyph: gen_app_scr75_c155))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c156, value: appStore.count(gen_app_scr75_c156).toString(), sub: gen_app_scr75_c157, glyph: gen_app_scr75_c158)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c159, value: appStore.count(gen_app_scr75_c159).toString(), sub: gen_app_scr75_c160, glyph: gen_app_scr75_c161))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c162, value: appStore.count(gen_app_scr75_c162).toString(), sub: gen_app_scr75_c163, glyph: gen_app_scr75_c164)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c165, value: appStore.count(gen_app_scr75_c165).toString(), sub: gen_app_scr75_c166, glyph: gen_app_scr75_c167))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c168, value: appStore.count(gen_app_scr75_c168).toString(), sub: gen_app_scr75_c169, glyph: gen_app_scr75_c170)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c171, value: appStore.count(gen_app_scr75_c171).toString(), sub: gen_app_scr75_c172, glyph: gen_app_scr75_c173))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c174, value: appStore.count(gen_app_scr75_c174).toString(), sub: gen_app_scr75_c175, glyph: gen_app_scr75_c176)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c177, value: appStore.count(gen_app_scr75_c177).toString(), sub: gen_app_scr75_c178, glyph: gen_app_scr75_c179))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c180, value: appStore.count(gen_app_scr75_c180).toString(), sub: gen_app_scr75_c181, glyph: gen_app_scr75_c182)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c183, value: appStore.count(gen_app_scr75_c183).toString(), sub: gen_app_scr75_c184, glyph: gen_app_scr75_c185))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c186, value: appStore.count(gen_app_scr75_c186).toString(), sub: gen_app_scr75_c187, glyph: gen_app_scr75_c188)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c189, value: appStore.count(gen_app_scr75_c189).toString(), sub: gen_app_scr75_c190, glyph: gen_app_scr75_c191))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c192, value: appStore.count(gen_app_scr75_c192).toString(), sub: gen_app_scr75_c193, glyph: gen_app_scr75_c194)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c195, value: appStore.count(gen_app_scr75_c195).toString(), sub: gen_app_scr75_c196, glyph: gen_app_scr75_c197))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c198, value: appStore.count(gen_app_scr75_c198).toString(), sub: gen_app_scr75_c199, glyph: gen_app_scr75_c200)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c201, value: appStore.count(gen_app_scr75_c201).toString(), sub: gen_app_scr75_c202, glyph: gen_app_scr75_c203))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c204, value: appStore.count(gen_app_scr75_c204).toString(), sub: gen_app_scr75_c205, glyph: gen_app_scr75_c206)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c207, value: appStore.count(gen_app_scr75_c207).toString(), sub: gen_app_scr75_c208, glyph: gen_app_scr75_c209))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c210, value: appStore.count(gen_app_scr75_c210).toString(), sub: gen_app_scr75_c211, glyph: gen_app_scr75_c212)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr75_c213, value: appStore.count(gen_app_scr75_c213).toString(), sub: gen_app_scr75_c214, glyph: gen_app_scr75_c215))), const SizedBox(width: 12), const Expanded(child: SizedBox())]))),
      ],
    );
  }
}
