// בדיקת-Golden · safetyKitItems — אפיון-חצב (חוק-4). מייבאת רק את האטום.
import 'safety_kit_items.dart';
import '../dart-data/k_lipskey_catalog-table.dart';
void _eq(String got, String want, String lbl){ if(got!=want) throw StateError('FAIL [$lbl]: got=$got want=$want'); }
void main(){
  var n=0;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[], const <LipskeyCatalogProduct>[])).toString(), '[]', '#0'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'a', nameHe: 'a', nameEn: 'a', categoryHe: 'a', categoryEn: 'a', categoryEmoji: 'a', page: 0),const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)], const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'a', nameHe: 'a', nameEn: 'a', categoryHe: 'a', categoryEn: 'a', categoryEmoji: 'a', page: 0),const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)])).toString(), '[]', '#1'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)], const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)])).toString(), '[]', '#2'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[], const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'a', nameHe: 'a', nameEn: 'a', categoryHe: 'a', categoryEn: 'a', categoryEmoji: 'a', page: 0),const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)])).toString(), '[]', '#3'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[], const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)])).toString(), '[]', '#4'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'a', nameHe: 'a', nameEn: 'a', categoryHe: 'a', categoryEn: 'a', categoryEmoji: 'a', page: 0),const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)], const <LipskeyCatalogProduct>[])).toString(), '[Instance of \'LipskeyCatalogProduct\', Instance of \'LipskeyCatalogProduct\']', '#5'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'a', nameHe: 'a', nameEn: 'a', categoryHe: 'a', categoryEn: 'a', categoryEmoji: 'a', page: 0),const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)], const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)])).toString(), '[Instance of \'LipskeyCatalogProduct\']', '#6'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)], const <LipskeyCatalogProduct>[])).toString(), '[Instance of \'LipskeyCatalogProduct\']', '#7'); n++;
  _eq((safetyKitItems(const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)], const <LipskeyCatalogProduct>[const LipskeyCatalogProduct(sku: 'a', nameHe: 'a', nameEn: 'a', categoryHe: 'a', categoryEn: 'a', categoryEmoji: 'a', page: 0),const LipskeyCatalogProduct(sku: 'b', nameHe: 'b', nameEn: 'b', categoryHe: 'b', categoryEn: 'b', categoryEmoji: 'b', page: 1)])).toString(), '[]', '#8'); n++;
  print('✓ safetyKitItems: '+n.toString()+' Golden');
}
