import '../dart-data-maor/amount-in-words-sockets.dart' as sk_amount_in_words;
// בדיקת-חוזה (רתמת-זהב) · amountInWords — מייבאת אך ורק את האטום-שלה (חוק-4).
// שכבה א׳: 12 דוגמאות-החוזה verbatim ממקור-ה-JS new/atoms/amount-in-words.test.mjs
//   (כל הקלטים לא-מספריים ⇒ Number.isFinite=false ⇒ המחרוזת חוזרת כמות-שהיא).
// שכבה ב׳: קלטים מספריים — הפלטים הוקלטו מהרצת מקור-ה-JS עצמו (ground truth),
//   מוכיחים שהזהב תופס גם את מסלול-החישוב, לא רק את הנפילה. אם עובר ⇒ Dart≡JS.
// הרצה: dart run --enable-asserts new/dart-maor/amount-in-words_test.dart  ⇒ exit 0
import 'amount-in-words.dart';

void _eq(String got, String want, String label) {
  if (got != want) {
    throw StateError('FAIL [$label]: got="$got" want="$want"');
  }
}

void main() {
  var n = 0;

  // — שכבה א׳: 12 דוגמאות-החוזה verbatim (amount-in-words.test.mjs) —
  _eq(amountInWords('', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), '', '1 empty');                                            n++;
  _eq(amountInWords('אבג', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אבג', '2 heb-word');                                   n++;
  _eq(amountInWords('כהן לוי', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'כהן לוי', '3 heb-name');                           n++;
  _eq(amountInWords('abc', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'abc', '4 abc');                                        n++;
  _eq(amountInWords('a@b.com', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'a@b.com', '5 email');                              n++;
  _eq(amountInWords('2026-08-24', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), '2026-08-24', '6 date');                         n++;
  _eq(amountInWords('2026-08-24T12:00:00', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), '2026-08-24T12:00:00', '7 datetime');   n++;
  _eq(amountInWords('0501234567', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), '0501234567', '8 phone');                        n++;
  _eq(amountInWords('03-1234567', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), '03-1234567', '9 phone2');                       n++;
  _eq(amountInWords('https://x.co', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'https://x.co', '10 url');                     n++;
  _eq(amountInWords('שלום עולם', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שלום עולם', '11 heb-sentence');                 n++;
  _eq(amountInWords('12', sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), '12', '12 numeric-string-stays');                        n++;

  // — שכבה ב׳: מסלול-החישוב (₪), פלטים מהרצת מקור-ה-JS —
  _eq(amountInWords(0, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אפס שקלים', 'n0');                                         n++;
  _eq(amountInWords(1, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שקל אחד', 'n1');                                           n++;
  _eq(amountInWords(2, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שני שקלים', 'n2');                                         n++;
  _eq(amountInWords(3, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שלושה שקלים', 'n3');                                       n++;
  _eq(amountInWords(10, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'עשרה שקלים', 'n10');                                      n++;
  _eq(amountInWords(11, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אחד עשר שקלים', 'n11');                                   n++;
  _eq(amountInWords(19, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'תשעה עשר שקלים', 'n19');                                  n++;
  _eq(amountInWords(20, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'עשרים שקלים', 'n20');                                     n++;
  _eq(amountInWords(21, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'עשרים ואחד שקלים', 'n21');                               n++;
  _eq(amountInWords(100, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'מאה שקלים', 'n100');                                     n++;
  _eq(amountInWords(101, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'מאה ואחד שקלים', 'n101');                               n++;
  _eq(amountInWords(200, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'מאתיים שקלים', 'n200');                                  n++;
  _eq(amountInWords(999, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'תשע מאות תשעים ותשעה שקלים', 'n999');                   n++;
  _eq(amountInWords(1000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אלף שקלים', 'n1000');                                   n++;
  _eq(amountInWords(1001, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אלף ואחד שקלים', 'n1001');                             n++;
  _eq(amountInWords(2000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אלפיים שקלים', 'n2000');                                n++;
  _eq(amountInWords(3000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שלושת אלפים שקלים', 'n3000');                          n++;
  _eq(amountInWords(5000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'חמשת אלפים שקלים', 'n5000');                           n++;
  _eq(amountInWords(21000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'עשרים ואחד אלף שקלים', 'n21000');                     n++;
  _eq(amountInWords(100000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'מאה אלף שקלים', 'n100000');                          n++;
  _eq(amountInWords(1000000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'מיליון שקלים', 'n1e6');                              n++;
  _eq(amountInWords(2000000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שני מיליון שקלים', 'n2e6');                         n++;
  _eq(amountInWords(5000000, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'חמישה מיליון שקלים', 'n5e6');                       n++;
  _eq(amountInWords(999999999, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T),
      'תשע מאות תשעים ותשעה מיליון תשע מאות תשעים ותשעה אלף תשע מאות תשעים ותשעה שקלים', 'nMax'); n++;

  // — שכבה ב׳: אגורות ונשיאת-עיגול —
  _eq(amountInWords(5.5, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'חמישה שקלים ו-חמישים אגורות', 'f5.5');                  n++;
  _eq(amountInWords(5.995, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שישה שקלים', 'f5.995-carry');                          n++;
  _eq(amountInWords(0.5, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אפס שקלים ו-חמישים אגורות', 'f0.5');                    n++;
  _eq(amountInWords(1.01, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שקל אחד ו-אגורה אחת', 'f1.01');                        n++;
  _eq(amountInWords(0.99, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'אפס שקלים ו-תשעים ותשע אגורות', 'f0.99');             n++;
  _eq(amountInWords(12.34, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שנים עשר שקלים ו-שלושים וארבע אגורות', 'f12.34');    n++;
  _eq(amountInWords(2.02, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שני שקלים ו-שתי אגורות', 'f2.02');                     n++;
  _eq(amountInWords(1.5, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T), 'שקל אחד ו-חמישים אגורות', 'f1.5');                      n++;

  // — שכבה ב׳: דולר/סנט (currency='$') —
  _eq(amountInWords(1, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'דולר אחד', 'd1');                                     n++;
  _eq(amountInWords(2, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'שני דולרים', 'd2');                                   n++;
  _eq(amountInWords(5, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'חמישה דולרים', 'd5');                                 n++;
  _eq(amountInWords(1.01, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'דולר אחד ו-אחד סנט', 'd1.01');                    n++;
  _eq(amountInWords(2.02, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'שני דולרים ו-שניים סנט', 'd2.02');                n++;
  _eq(amountInWords(0.5, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'אפס דולרים ו-חמישים סנט', 'd0.5');                 n++;
  _eq(amountInWords(5.5, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T, '\$'), 'חמישה דולרים ו-חמישים סנט', 'd5.5');               n++;

  // assert חי (חוק: --enable-asserts) — מוכיח שהמנגנון פעיל.
  assert(amountInWords(1, sk_amount_in_words.amountInWords_ONES, sk_amount_in_words.amountInWords_TEENS, sk_amount_in_words.amountInWords_TENS, sk_amount_in_words.amountInWords_HUNDREDS, sk_amount_in_words.amountInWords_ONES_F, sk_amount_in_words.amountInWords_TEENS_F, sk_amount_in_words.amountInWords_THOUSAND_CONSTRUCT, sk_amount_in_words.amountInWords_T) == 'שקל אחד', 'assert-live guard');

  print('OK amountInWords: $n asserts passed');
}
