#!/usr/bin/env node
/**
 * step intent-kernel: one registry (liba/intents/registry.json) -> the page's table (liba/src/00-intents.js), the bubble's
 * table (android/.../LibaIntents.kt) and the help ליבה reads aloud. A command cannot be announced without a handler, and
 * a phrase cannot belong to two commands on the same side.
 *   node liba/intents/build.mjs            write both
 *   node liba/intents/build.mjs --check    exit 1 if either file is not what the registry makes
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const REG = join(root, 'liba/intents/registry.json'), PAGE = join(root, 'liba/src/00-intents.js'), KT = join(root, 'android/app/src/main/java/il/liba/app/LibaIntents.kt')
const CHECK = process.argv.includes('--check')
const reg = JSON.parse(readFileSync(REG, 'utf8'))

// the pattern language: (a|b) one of, [a|b] optional one of; the result is every exact phrase it stands for
export function expand(p) {
  const m = /[(\[]/.exec(p); if (!m) return [p.replace(/\s+/g, ' ').trim()]
  const open = m.index, close = p.indexOf(m[0] === '(' ? ')' : ']', open)
  if (close < 0) throw new Error('intents: unclosed group in "' + p + '"')
  const alts = p.slice(open + 1, close).split('|'), head = p.slice(0, open), tail = p.slice(close + 1)
  if (m[0] === '[') alts.push('')
  return [...new Set(alts.flatMap(a => expand(head + a + tail)))].filter(Boolean)
}
// the one normalization, shared by the page and the table: punctuation, bidi marks, niqqud, spacing, "ליבא"
export const norm = t => String(t || '').replace(/[‎‏‪-‮⁦-⁩﻿֑-ׇ]/g, '').replace(/[?!.,:;"'׳״]/g, '').replace(/\s+/g, ' ').trim().replace(/(^|\s)ליבא(?=\s|$)/g, '$1ליבה')

const FAMILY_ORDER = ['דיבור', 'משימות', 'בנייה', 'אנשים', 'שקט', 'קול', 'זיכרון', 'שליחה', 'חושים', 'בקרה', 'עזרה']
const errs = []
const intents = reg.intents.map(i => ({ ...i, status: i.status || 'live', exact: (i.exact || []).flatMap(expand).map(norm), prefix: (i.prefix || []).flatMap(expand).map(norm), suffix: (i.suffix || []).flatMap(expand).map(norm) }))
// a phrase belongs to one command per side (app phrases are heard by the bubble first, page phrases by the page)
for (const side of ['app', 'page']) {
  const seen = new Map()
  for (const i of intents.filter(x => x.where === side && x.status === 'live')) for (const ph of i.exact) {
    if (seen.has(ph) && seen.get(ph) !== i.id) errs.push(`"${ph}" שייך גם ל-${seen.get(ph)} וגם ל-${i.id}`); seen.set(ph, i.id)
  }
}
for (const i of intents) {
  if (!['page', 'app', 'claude'].includes(i.where)) errs.push(i.id + ': where לא מוכר')
  if (i.where === 'page' && i.status === 'live' && !i.handler) errs.push(i.id + ': כוונה בדף בלי handler')
  if (i.where === 'claude' && i.status === 'live' && !i.rule) errs.push(i.id + ': כוונה לקלוד בלי כלל בפרוטוקול')
  if (i.status === 'live' && !i.exact.length && !i.prefix.length && !i.suffix.length) errs.push(i.id + ': אין אף ביטוי')
}
if (errs.length) { console.error('intents:\n  ' + errs.join('\n  ')); process.exit(1) }

// help: only what is live, by family, in a fixed order
const fams = FAMILY_ORDER.filter(f => (reg.families || {})[f] || intents.some(i => i.family === f && i.status === 'live' && i.help))
const help = fams.map(f => [f, (reg.families || {})[f] || intents.filter(i => i.family === f && i.status === 'live' && i.help).map(i => i.help).join(', ')])

const js = s => JSON.stringify(s)
const pageRows = intents.filter(i => i.status === 'live' && i.where !== 'app').map(i => '  ' + js({ id: i.id, where: i.where, when: i.when || '', exact: i.exact, prefix: i.prefix, suffix: i.suffix, handler: i.handler || '', confirm: !!i.confirm, pass: !!i.pass, requires: i.requires || [], lead: i.lead || [], leadRequired: !!i.leadRequired }))
const page = `// @anchor: intents
// GENERATED by liba/intents/build.mjs from liba/intents/registry.json - do not edit here
const INTENTS=Object.freeze([
${pageRows.join(',\n')}
]);
const INTENT_HELP=Object.freeze(${js(help)});
`
const appRows = intents.filter(i => i.status === 'live' && i.where === 'app').flatMap(i => i.exact.map(ph => `        ${js(ph)} to ${js(i.id)}`))
const kt = `// GENERATED by liba/intents/build.mjs from liba/intents/registry.json - do not edit here
package il.liba.app

/** step intent-kernel: the bubble's own commands, from the same registry as the page's and the help */
object LibaIntents {
    private val EXACT = mapOf(
${appRows.join(',\n')}
    )
    fun norm(t: String): String = t.replace(Regex("[\\u200e\\u200f\\u202a-\\u202e\\u2066-\\u2069\\ufeff\\u0591-\\u05c7]"), "").replace(Regex("[?!.,:;\\"'׳״]"), "").replace(Regex("\\\\s+"), " ").trim()
    fun match(t: String): String? = EXACT[norm(t)]
}
`
if (CHECK) {
  const bad = [[PAGE, page], [KT, kt]].filter(([f, want]) => { try { return readFileSync(f, 'utf8') !== want } catch { return true } }).map(([f]) => f.replace(root + '/', ''))
  if (bad.length) { console.error('intents: לא תואם לרישום - הרץ node liba/intents/build.mjs: ' + bad.join(', ')); process.exit(1) }
} else { writeFileSync(PAGE, page); writeFileSync(KT, kt) }
const live = intents.filter(i => i.status === 'live')
console.log(`intents: ${live.length} כוונות חיות (${live.filter(i => i.where === 'page').length} בדף, ${live.filter(i => i.where === 'app').length} בבועה, ${live.filter(i => i.where === 'claude').length} לקלוד) · ${intents.length - live.length} מתוכננות · ${help.length} משפחות בעזרה${CHECK ? ' · נקי' : ''}`)
