// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent5_c0 = 'תקופה';
const String gen_app_ent5_c1 = '8 שדות';
const String gen_app_ent5_c2 = '🗂️';
const String gen_app_ent5_c3 = 'שמירה';
const String gen_app_ent5_c4 = 'עדכון';
const String gen_app_ent5_c5 = 'פרטי הרשומה';
const String gen_app_ent5_c6 = 'רשומות';
const String gen_app_ent5_c7 = 'אין תקופה עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent5_c8 = 'לא נמצאו רשומות תואמות';
const String gen_app_ent5_c9 = 'שנת לימודים';
const String gen_app_ent5_c10 = 'שם תקופה';
const String gen_app_ent5_c11 = 'סוג';
const String gen_app_ent5_c12 = 'תאריך התחלה';
const String gen_app_ent5_c13 = 'תאריך סיום';
const String gen_app_ent5_c14 = 'משקל ציונים';
const String gen_app_ent5_c15 = 'תאריך נעילה';
const String gen_app_ent5_c16 = 'סטטוס';
const String gen_app_ent5_c17 = 'סטטוס בא';
