// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent24_c0 = 'נוכחות עובד';
const String gen_app_ent24_c1 = '9 שדות';
const String gen_app_ent24_c2 = '🗂️';
const String gen_app_ent24_c3 = 'שמירה';
const String gen_app_ent24_c4 = 'עדכון';
const String gen_app_ent24_c5 = 'פרטי הרשומה';
const String gen_app_ent24_c6 = 'רשומות';
const String gen_app_ent24_c7 = 'אין נוכחות עובד עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent24_c8 = 'עובד';
const String gen_app_ent24_c9 = 'תאריך';
const String gen_app_ent24_c10 = 'תאריך לתצוגה';
const String gen_app_ent24_c11 = 'כניסה';
const String gen_app_ent24_c12 = 'יציאה';
const String gen_app_ent24_c13 = 'שעות';
const String gen_app_ent24_c14 = 'היעדרות';
const String gen_app_ent24_c15 = 'איחור';
const String gen_app_ent24_c16 = 'מיקום';
const String gen_app_ent24_c17 = 'אישור';
