// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_scr72_c0 = 'דשבורד מנהל';
const String gen_app_scr72_c1 = '5 מדדים · סקירת-על';
const String gen_app_scr72_c2 = '📊';
const String gen_app_scr72_c3 = 'תלמיד';
const String gen_app_scr72_c4 = '22 שדות · 7 שלבים';
const String gen_app_scr72_c5 = '🗂️';
const String gen_app_scr72_c6 = 'קבוצת תלמידים';
const String gen_app_scr72_c7 = '8 שדות';
const String gen_app_scr72_c8 = '🗂️';
const String gen_app_scr72_c9 = 'נוכחות עובד';
const String gen_app_scr72_c10 = '9 שדות';
const String gen_app_scr72_c11 = '🗂️';
const String gen_app_scr72_c12 = 'נוכחות';
const String gen_app_scr72_c13 = '12 שדות · 7 שלבים';
const String gen_app_scr72_c14 = '🗂️';
const String gen_app_scr72_c15 = 'ציונים';
const String gen_app_scr72_c16 = '14 שדות · 4 שלבים';
const String gen_app_scr72_c17 = '🗂️';
