// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_scr75_c0 = 'דשבורד תפעול';
const String gen_app_scr75_c1 = '📊';
const String gen_app_scr75_c2 = 'מערכת שעות';
const String gen_app_scr75_c3 = '15 שדות';
const String gen_app_scr75_c4 = '🗂️';
const String gen_app_scr75_c5 = 'מסלול הסעה';
const String gen_app_scr75_c6 = '11 שדות';
const String gen_app_scr75_c7 = '🗂️';
const String gen_app_scr75_c8 = 'שיוך הסעה';
const String gen_app_scr75_c9 = '8 שדות';
const String gen_app_scr75_c10 = '🗂️';
const String gen_app_scr75_c11 = 'נסיעת הסעה';
const String gen_app_scr75_c12 = '11 שדות · 3 שלבים';
const String gen_app_scr75_c13 = '🗂️';
const String gen_app_scr75_c14 = 'בקשת תחזוקה';
const String gen_app_scr75_c15 = '14 שדות · 4 שלבים';
const String gen_app_scr75_c16 = '🗂️';
const String gen_app_scr75_c17 = '5 מדדים · סקירת-על';
