// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_scr75_c0 = 'דשבורד תפעול';
const String gen_app_scr75_c1 = '5 מדדים · סקירת-על';
const String gen_app_scr75_c2 = '📊';
const String gen_app_scr75_c3 = 'מערכת שעות';
const String gen_app_scr75_c4 = '15 שדות';
const String gen_app_scr75_c5 = '🗂️';
const String gen_app_scr75_c6 = 'מסלול הסעה';
const String gen_app_scr75_c7 = '11 שדות';
const String gen_app_scr75_c8 = '🗂️';
const String gen_app_scr75_c9 = 'שיוך הסעה';
const String gen_app_scr75_c10 = '8 שדות';
const String gen_app_scr75_c11 = '🗂️';
const String gen_app_scr75_c12 = 'נסיעת הסעה';
const String gen_app_scr75_c13 = '11 שדות · 3 שלבים';
const String gen_app_scr75_c14 = '🗂️';
const String gen_app_scr75_c15 = 'בקשת תחזוקה';
const String gen_app_scr75_c16 = '14 שדות · 4 שלבים';
const String gen_app_scr75_c17 = '🗂️';
