// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent49_c0 = 'חבר ספרייה';
const String gen_app_ent49_c1 = '7 שדות';
const String gen_app_ent49_c2 = '🗂️';
const String gen_app_ent49_c3 = 'שמירה';
const String gen_app_ent49_c4 = 'פרטי הרשומה';
const String gen_app_ent49_c5 = 'רשומות';
const String gen_app_ent49_c6 = 'אין חבר ספרייה עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent49_c7 = 'חבר ספרייה';
const String gen_app_ent49_c8 = 'תלמיד';
const String gen_app_ent49_c9 = 'תלמיד';
const String gen_app_ent49_c10 = 'עובד';
const String gen_app_ent49_c11 = 'עובד';
const String gen_app_ent49_c12 = 'כיתה';
const String gen_app_ent49_c13 = 'כיתה';
const String gen_app_ent49_c14 = 'מספר חבר';
const String gen_app_ent49_c15 = 'מגבלת השאלה';
const String gen_app_ent49_c16 = 'קנסות';
const String gen_app_ent49_c17 = 'סטטוס';
