// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent37_c0 = 'התאמה';
const String gen_app_ent37_c1 = '9 שדות';
const String gen_app_ent37_c2 = '🗂️';
const String gen_app_ent37_c3 = 'שמירה';
const String gen_app_ent37_c4 = 'עדכון';
const String gen_app_ent37_c5 = 'פרטי הרשומה';
const String gen_app_ent37_c6 = 'רשומות';
const String gen_app_ent37_c7 = 'אין התאמה עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent37_c8 = 'לא נמצאו רשומות תואמות';
const String gen_app_ent37_c9 = 'תלמיד';
const String gen_app_ent37_c10 = 'מקצוע';
const String gen_app_ent37_c11 = 'סוג התאמה';
const String gen_app_ent37_c12 = 'תוקף';
const String gen_app_ent37_c13 = 'מבחנים';
const String gen_app_ent37_c14 = 'שיעורים';
const String gen_app_ent37_c15 = 'הוראות';
const String gen_app_ent37_c16 = 'בעלי הרשאה';
const String gen_app_ent37_c17 = 'אישור';
