// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_nl_card_glyph = '🔹';
const String gen_nl_card_title = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_card_sub = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_card_toast = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_card_glyph2 = '🔹';
const String gen_nl_card_message = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_other_label = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_other_label2 = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_other_toast = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_header_title = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_other_text = 'לוח בקרה לניהול עסק עם הזמנות';
const String gen_nl_card_stage_label = 'הזמנות'; // t_d0776cb6
const String gen_nl_card_items_label = 'הזמנות'; // t_d0776cb6
const String gen_nl_card_sum_label = 'הזמנות'; // t_d0776cb6
const String gen_nl_card_toast2 = 'הזמנות'; // t_d0776cb6
const String gen_nl_card_glyph3 = '🔹';
const String gen_nl_card_name = 'לקוחות'; // t_1881898b
const String gen_nl_card_sub_label = 'לקוחות'; // t_1881898b
const String gen_nl_card_credit_line = 'לקוחות'; // t_1881898b
const String gen_nl_card_toast3 = 'לקוחות'; // t_1881898b
const String gen_nl_profile_title = 'מדדים';
const String gen_nl_profile_sub = 'מדדים';
const String gen_nl_banner_sub = 'המחולל למד מהאטומים ומהלוחות ובחר לבד לפי משמעות';
const String gen_nl_app_bar_title = 'הירו 🎯 לוח בקרה לניהול עסק עם הזמנות | נבנה מתיאור חופשי';
