#!/usr/bin/env node
/**
 * step shabbat-engine: twenty years of holy days (Israel: one day of yom tov) from the Hebrew calendar that node already
 * carries (ICU), offline, into the two places that need them: liba/src/00-moadim.js (the page) and
 * android/.../res/raw/moadim.json (the phone). Shabbat itself is not listed - every Saturday is one.
 *   node tools/gen-moadim.mjs          write
 *   node tools/gen-moadim.mjs --check  fail if either file differs from what it would write
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')
const YT = { 'Tishri-1': 'ראש השנה', 'Tishri-2': 'ראש השנה', 'Tishri-10': 'יום כיפור', 'Tishri-15': 'סוכות', 'Tishri-22': 'שמיני עצרת',
  'Nisan-15': 'פסח', 'Nisan-21': 'שביעי של פסח', 'Sivan-6': 'שבועות' }
const f = new Intl.DateTimeFormat('en-u-ca-hebrew', { month: 'long', day: 'numeric', timeZone: 'UTC' })
const days = {}
for (let t = Date.UTC(2026, 0, 1); t <= Date.UTC(2046, 11, 31); t += 864e5) {
  const p = f.formatToParts(new Date(t + 12 * 3600e3)); const k = p.find(x => x.type === 'month').value + '-' + p.find(x => x.type === 'day').value
  if (YT[k]) days[new Date(t).toISOString().slice(0, 10)] = YT[k]
}
const n = Object.keys(days).length
if (n !== 21 * 8) { console.error('gen-moadim: expected ' + 21 * 8 + ' days, got ' + n); process.exit(1) }
const json = JSON.stringify({ v: 1, israel: true, from: '2026-01-01', to: '2046-12-31', days }) + '\n'
const js = `// @anchor: moadim\n// GENERATED by tools/gen-moadim.mjs - do not edit here\nconst MOADIM=Object.freeze(${JSON.stringify(days)});\n`
const out = [[join(ROOT, 'liba/src/00-moadim.js'), js], [join(ROOT, 'android/app/src/main/res/raw/moadim.json'), json]]
if (CHECK) { const bad = out.filter(([p, w]) => { try { return readFileSync(p, 'utf8') !== w } catch { return true } }); if (bad.length) { console.error('gen-moadim: לא תואם - הרץ node tools/gen-moadim.mjs'); process.exit(1) } console.log('gen-moadim: ' + n + ' ימים · נקי') }
else { mkdirSync(dirname(out[1][0]), { recursive: true }); out.forEach(([p, w]) => writeFileSync(p, w)); console.log('gen-moadim: ' + n + ' ימים טובים, 2026–2046') }
