// 📦 דאטה-תוכן (חולל ע"י screen-lift, הכרעה-11: מנוע-לא-נחיל) · features__internal_card__full_internal_card
// מוצא: features__internal_card__full_internal_card.dart — כל מחרוזת-תוכן שהייתה צרובה ב-widget, ממופתחת פר-מנגנון.

const cardViewContent = (
  ngyehBLa1: 'נגיעה ב📋 (לא קופץ) — המפרט/תקן/אזהרה מחליף את התמונה ',
  bmqwTabyLmebr2: 'במקום · טאבים למעבר',
  tplMcykhToRight3: 'משיכה ${toRight ? ',
  cmalh4: 'שמאלה',
  tplMhMtjbrLxd5: ' מה מתחבר לצד ${toRight ? ',
  cmal6: 'שמאל',
  mfrt7: 'מפרט · ',
  jzwrMqxtMwtbe8: ' חזור · מק״ט מוטבע על התמונה · נגיעה=גלריה',
  txt9: '📋',
  br10: 'ברך',
  zwwyt11: 'זווית',
  txt12: '🦵',
  mse13: 'מסעף',
  hstefwt14: 'הסתעפות',
  txt15: '🔱',
  xynwr16: 'צינור',
  xnrt17: 'צנרת',
  txt18: '🟫',
  mxrh19: 'מצרה',
  txt20: '🔻',
  nyfl21: 'ניפל',
  txt22: '🔗',
  fqq23: 'פקק',
  mxmd24: 'מצמד',
  mjbr25: 'מחבר',
  mwfh26: 'מופה',
  txt27: '🧷',
  aw28: 'אום',
  txt29: '🔩',
  mhMtjbrLxd30: 'מה מתחבר לצד שמאל',
  mhMtjbrLxd31: 'מה מתחבר לצד ימין',
  tplLabelHjlq32: '🔗 $label · החלק ↔',
  ayTwaYcyr33: 'אין תואם ישיר',
  tplDnMxm34: '$dn מ״מ',
  hjlqAwHqc35: 'החלק או הקש נקודה להחלפת מידה',
  txt36: '📐',
  mfrt37: 'מפרט',
  tq38: 'תקן',
  azhrh39: 'אזהרה',
  txt40: '🧱',
  jwmr41: 'חומר',
  txt42: '🌡️',
  tmfx43: 'טמפ׳',
  ayNtwny44: 'אין נתונים',
  txt45: '🎛️',
  hgdrh46: 'הגדרה',
  glgly47: 'גלגלים',
  qwtrZwwytAwr48: 'קוטר · זווית · אורך · כמות',
  symw49: 'סימון',
  txt50: '🧩',
  wryanty51: 'וריאנטים',
  mtjbrLx52: 'מתחבר ל־',
  tplMhCmtjbrLmydh53: 'מה שמתחבר למידה $dn:',
  hwrawtjybwr54: 'הוראות-חיבור',
  txt55: '🛠️',
  clbyHtqnh56: 'שלבי התקנה',
  tplKitmustJwbh57: '${kit.must} חובה',
  tplKitoptionalAwfxyh58: '${kit.optional} אופציה',
  tplKittoolsKly59: '${kit.tools} כלים',
  txt60: '🧰',
  erktAbyzry61: 'ערכת אביזרים',
  mfrtJwmry62: 'מפרט חומרים',
  mfrtHndsy63: 'מפרט הנדסי',
  tmfrtwrh64: 'טמפרטורה',
  tplEdSpecmaxTempCroundC65: 'עד ${spec.maxTempC.round()}°C',
  drycwtTqynwt66: 'דרישות תקינות',
  azhrwt67: 'אזהרות',
  abyzryMclymy68: 'אביזרים משלימים',
  txt69: '💰',
  herktMjyr70: 'הערכת מחיר',
  tplHerkhLfyQtgwryh71: 'הערכה לפי קטגוריה · ${formatCatalogPrice(base, s)}',
  tplShxkFormatCatalogPricel72: 'סה״כ ${formatCatalogPrice(lineTotal, s)}',
  yjydh73: 'יחידה',
  kmwt74: 'כמות',
  acr75: 'אשר',
  hwsLsl76: 'הוסף לסל',
  tplNwsfwQtyUnitKey77: 'נוספו $qty × $unitKey לסל',
  nwsLsl78: 'נוסף לסל',
  hajrwMwdgcHqc79: 'האחרון מודגש · הקש עיגול=בחירה · הקש מודגש=הסרה · +=הוספה',
  txt80: '📦',
);

