// 📦 דאטה-תוכן (חולל ע"י screen-lift, הכרעה-11: מנוע-לא-נחיל) · screens__courier_reports_tab
// מוצא: screens__courier_reports_tab.dart — כל מחרוזת-תוכן שהייתה צרובה ב-widget, ממופתחת פר-מנגנון.

const courierReportsTabContent = (
  title: '📊 דוחות',
  subtitle: 'נתונים חיים ממנוע ההזמנות המשותף — ללא המצאות',
  t01: 'מסירות ישנות ללא ייחוס אינן נספרות',
  t02: 'אין עדיין מדידות זמן — הזמן נמדד אוטומטית מרגע אישור האיסוף ועד המסירה ללקוח.',
  historyTitle: 'היסטוריית מסירות',
  emptyTitle: 'אין עדיין מסירות שהושלמו',
  t03: 'משלוח שיסומן "נמסר ללקוח" יופיע כאן',
  sendReport: '🏪 שלח דוח-יומי לחנות',
  t04: 'נסח דוח עם AI',
  t05: 'הדוח נשלח כהודעה אמיתית לשיחת "חנות ליפסקי" (מנוע הצ׳אט המשותף — החנות משתתפת בשיחה) + התראת-פעמון לחנות. מוני המסירות והערך מיוחסים לשליח המחובר בלבד, בלי המצאות.',
  tplStreakYmy11: '$streak ימים',
  nmsrw12: 'נמסרו ✅',
  feyly13: 'פעילים 🚚',
  POD14: 'POD 📸',
  BuildCoinsMwedwMcwt15: 'BuildCoins (מועדון משותף) 🪙',
  rxFeylwt16: 'רצף פעילות 🔥',
  msyrhracwnh17: 'מסירה-ראשונה 🎯',
  tplMtbewtMazOrgTermref18: 'מטבעות — מאזן ${orgTerm(ref, ',
  AppBrandclubHmcwtLkl19: ', AppBrand.club)} המשותף לכל התפקידים במכשיר (אינו נצבר לשליח בנפרד); הרצף ו-% מסירה-ראשונה נמדדים מחותמות שעון-המשלוחים — עדיין אין מסירות שנמדדו.',
  tplAppBrandclubHmcwtLkl20: ', AppBrand.club)} המשותף לכל התפקידים במכשיר (אינו נצבר לשליח בנפרד); הרצף נמדד מחותמות שעון-המשלוחים. מסירה-ראשונה: $firstAttempt מתוך ${measuredDelivered.length} מסירות שנמדדו — ללא ניסיון חוזר.',
  tplShxkErCnmsr21: 'סה״כ ערך שנמסר על-ידי: ${fMoney(deliveredSum)}',
  msyrwtLfyYw22: '📅 מסירות לפי יום',
  ewdAyMsyrwt23: 'עוד אין מסירות שהושלמו — מסירה שתסומן "נמסר ללקוח" תופיע כאן.',
  ayMsyrwtCnmddw24: 'אין מסירות שנמדדו השבוע.',
  tplLlaJwtmtNoStamp25: '🗓️ ללא חותמת: $noStamp ${noStamp == 1 ? ',
  msyrwt26: 'מסירות',
  zmAyswMsyrh27: '⏱️ זמן איסוף→מסירה',
  tplMmwxeTimedlengthMsyrwt28: 'ממוצע (${timed.length} מסירות)',
  tplOid29: '📦 ${o.id}',
  txt30: '📭',
  cljDwjywmyLjnwt31: 'שלח דוח-יומי לחנות',
  cwljLjnwtSykw32: 'שולח לחנות סיכום יומי כהודעת צ׳אט אמיתית + התראת-פעמון: כמה משלוחים נמסרו על-ידך, פעילים, POD וערך כספי. המספרים מיוחסים לשליח המחובר בלבד.',
  cljDwjYwmy33: 'שלח דוח יומי לחנות',
  ayClyjMjwbr34: 'אין שליח מחובר',
  tplDwjywClyjSdisplayName35: 'דוח-יום — שליח ${s.displayName}',
  tplNmsrwHywNmdd36: '✅ נמסרו היום (נמדד): $deliveredToday',
  tplShxkNmsrwElydy37: '📦 סה״כ נמסרו על-ידי: ${mine.length}',
  tplMclwjyFeylyKll38: '🚚 משלוחים פעילים (כלל המערכת): $active',
  tplPODClyPodCount39: '📸 POD שלי: $podCount',
  tplErCnmsrFMoneydelivere40: '💰 ערך שנמסר: ${fMoney(deliveredSum)}',
  ayClyjMjwbr41: 'אין שליח מחובר — הדוח לא נשלח',
  tplErCnmsrElydy42: '💰 ערך שנמסר על-ידי: ${fMoney(deliveredSum)}',
  cyjtHjnwtLa43: 'שיחת החנות לא נמצאה — הדוח לא נשלח',
  txt44: '📋',
  dwjYwmyMhclyj45: 'דוח יומי מהשליח 🛵',
  tplSdisplayNameNmsrwElydw46: '${s.displayName} — נמסרו על-ידו: ${mine.length} · פעילים: $active · ${fMoney(deliveredSum)}',
  hdwjNcljLjnwt47: '🏪 הדוח נשלח לחנות — שיחה + התראת-פעמון',
);

